# Generated by Django 3.1.5 on 2021-01-14 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='user_login',
        ),
    ]
